language: java

install: gradle wrapper --gradle-version 4.2
jdk:
  - openjdk8
before_install:
  - pip install --user codecov

after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)

branches:
  except:
    - appveyor